export default {
    users: [
        {
            id: 1,
            name: 'Logan Schowalter',
            email: 'admin@example.com',
            phone: '1987367298',
            occupation: 'CEO',
            role: 'admin',
        },
        {
            id: 2,
            name: 'Breanna Gibson',
            email: 'user1@user.com',
            phone: '1099238238',
            occupation: 'Marketing representitive',
            role: 'user',
        },
        {
            id: 3,
            name: 'Annamarie Mayer',
            email: 'user2@user.com',
            phone: '0839273718',
            occupation: 'Sales Manager',
            role: 'user',
        },
    ],
    categories: [
        {
            id: 1,
            name: 'Development',
            created_by: 1,
            created_at: new Date('2019-06-21'),
            updated_at: new Date('2019-06-21')
        },
        {
            id: 2,
            name: 'Sales and Marketing',
            created_by: 2,
            created_at: new Date('2019-06-21'),
            updated_at: new Date('2019-06-21')
        },
        {
            id: 3,
            name: 'Advertising',
            created_by: 1,
            created_at: new Date('2019-06-20'),
            updated_at: new Date('2019-06-20')
        },
        {
            id: 4,
            name: 'Environment',
            created_by: 3,
            created_at: new Date('2019-06-19'),
            updated_at: new Date('2019-06-19')
        },
    ],
    articles: [
        {
            id: 1,
            name: 'ReactJS programming',
            type: 'document',
            category_id: 1,
            created_by: 1,
            is_active: true,
            is_homepage: true,
            created_at: new Date('2019-06-20'),
            updated_at: new Date('2019-06-20'),
        },
        {
            id: 2,
            name: 'Javascript programming',
            type: 'document',
            category_id: 1,
            created_by: 2,
            is_active: true,
            is_homepage: true,
            created_at: new Date('2019-06-20'),
            updated_at: new Date('2019-06-20'),
        },
        {
            id: 3,
            name: 'Learn Business',
            type: 'document',
            category_id: 2,
            created_by: 3,
            is_active: true,
            is_homepage: true,
            created_at: new Date('2019-06-17'),
            updated_at: new Date('2019-06-17'),
        },
        {
            id: 4,
            name: 'Business Tricks',
            type: 'textentry',
            category_id: 2,
            created_by: 3,
            is_active: true,
            is_homepage: true,
            created_at: new Date('2019-06-15'),
            updated_at: new Date('2019-06-15'),
        },
        {
            id: 5,
            name: 'Developer Form',
            type: 'form',
            category_id: 1,
            created_by: 1,
            is_active: true,
            is_homepage: false,
            created_at: new Date('2019-06-18'),
            updated_at: new Date('2019-06-18'),
        },
        {
            id: 6,
            name: 'Google Ads Professional',
            type: 'document',
            category_id: 3,
            created_by: 1,
            is_active: true,
            is_homepage: false,
            created_at: new Date('2019-06-20'),
            updated_at: new Date('2019-06-20'),
        },
        {
            id: 7,
            name: 'Ads Tips',
            type: 'textentry',
            category_id: 3,
            created_by: 2,
            is_active: true,
            is_homepage: false,
            created_at: new Date('2019-06-21'),
            updated_at: new Date('2019-06-21'),
        },
        {
            id: 8,
            name: 'Cleaner form',
            type: 'form',
            category_id: 4,
            created_by: 1,
            is_active: true,
            is_homepage: false,
            created_at: new Date('2019-06-20'),
            updated_at: new Date('2019-06-20'),
        },
        {
            id: 9,
            name: 'Powerplant Engineer form',
            type: 'form',
            category_id: 4,
            created_by: 1,
            is_active: true,
            is_homepage: false,
            created_at: new Date('2019-06-19'),
            updated_at: new Date('2019-06-19'),
        },
        {
            id: 10,
            name: 'Greenhousing',
            type: 'document',
            category_id: 4,
            created_by: 1,
            is_active: true,
            is_homepage: true,
            created_at: new Date('2019-06-20'),
            updated_at: new Date('2019-06-20'),
        },
        {
            id: 11,
            name: 'Windpower planting',
            type: 'document',
            category_id: 4,
            created_by: 1,
            is_active: true,
            is_homepage: true,
            created_at: new Date('2019-06-13'),
            updated_at: new Date('2019-06-13'),
        },
    ],
    revisions: [
        {
            id: 1,
            content: 'documents/Coherent DMS-191923948.pdf',
            note: 'initial release',
            type: 'document',
            article_id: 1,
            created_by: 1,
            created_at: new Date('2019-06-20'),
        },
        {
            id: 2,
            content: 'file://developer.com/javascript.pdf',
            note: 'initial release',
            type: 'document',
            article_id: 2,
            created_by: 1,
            created_at: new Date('2019-06-20'),
        },
        {
            id: 3,
            content: 'file://business.com/learn.pdf',
            note: 'initial release',
            type: 'document',
            article_id: 3,
            created_by: 1,
            created_at: new Date('2019-06-17'),
        },
        {
            id: 4,
            content: '1. Make it clear.',
            note: 'initial release',
            type: 'textentry',
            article_id: 4,
            created_by: 2,
            created_at: new Date('2019-06-15'),
        },
        {
            id: 5,
            content: '<form><input type="text" value="" name="name" /></form>',
            note: 'initial release',
            type: 'form',
            article_id: 5,
            created_by: 1,
            created_at: new Date('2019-06-18'),
        },
        {
            id: 6,
            content: 'file://ads.com/google.pdf',
            note: 'initial release',
            type: 'document',
            article_id: 6,
            created_by: 3,
            created_at: new Date('2019-06-20'),
        },
        {
            id: 7,
            content: '1. Social media expert.',
            note: 'initial release',
            type: 'textentry',
            article_id: 7,
            created_by: 1,
            created_at: new Date('2019-06-21'),
        },
        {
            id: 8,
            content: '[{"type":"text","required":true,"label":"User Name","placeholder":"Input Username...","className":"form-control","name":"username","subtype":"text"},{"type":"text","subtype":"password","required":true,"label":"Password","placeholder":"Enter Password...","className":"form-control","name":"password"}]',
            note: 'initial release',
            type: 'form',
            article_id: 8,
            created_by: 1,
            created_at: new Date('2019-06-20'),
        },
        {
            id: 9,
            content: '<form><input type="text" value="" name="name" /></form>',
            note: 'initial release',
            type: 'form',
            article_id: 9,
            created_by: 1,
            created_at: new Date('2019-06-19'),
        },
        {
            id: 10,
            content: 'file://env/greenhousing.pdf',
            note: 'initial release',
            type: 'document',
            article_id: 10,
            created_by: 1,
            created_at: new Date('2019-06-20'),
        },
        {
            id: 11,
            content: 'file://env/windpower.pdf',
            note: 'initial release',
            type: 'document',
            article_id: 11,
            created_by: 1,
            created_at: new Date('2019-06-13'),
        },
        {
            id: 12,
            content: 'documents/Coherent DMS-192039158.pdf',
            note: 'change some content',
            type: 'document',
            article_id: 1,
            created_by: 3,
            created_at: new Date('2019-06-22'),
        },
        {
            id: 13,
            content: 'documents/Coherent DMS-192039372.pdf',
            note: 'add some content',
            type: 'document',
            article_id: 1,
            created_by: 2,
            created_at: new Date('2019-06-23'),
        },
        {
            id: 14,
            content: '1. Make it clear 2. Make it easy.',
            note: 'add tricks',
            type: 'textentry',
            article_id: 4,
            created_by: 2,
            created_at: new Date('2019-06-19'),
        },
        {
            id: 15,
            content: '<form><input type="text" value="ricky" name="name" /></form>',
            note: 'form submission',
            type: 'form',
            article_id: 5,
            created_by: 2,
            created_at: new Date('2019-06-20'),
        },
        {
            id: 16,
            content: '<form><input type="text" value="hello" name="name" /></form>',
            note: 'form submission',
            type: 'form',
            article_id: 5,
            created_by: 3,
            created_at: new Date('2019-06-20'),
        },
    ]
};
